# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  google_client_id: 237972700244-bn3b1l41jon2m97unfbnost07dv2cdeg.apps.googleusercontent.com
  google_client_secret: Xmj5H7TqThtOvhBiMxNQP8_4
  cors_path: ['localhost:4200']

test:
  google_client_id: 237972700244-bn3b1l41jon2m97unfbnost07dv2cdeg.apps.googleusercontent.com
  google_client_secret: Xmj5H7TqThtOvhBiMxNQP8_4
  cors_path: []

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%=ENV["GOOGLE_CLIENT_SECRET"]%>
  cors_path: <%=ENV["CORS_PATH"]%>